config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  get '/sitemap.xml', to: redirect("https://s3-us-west-1.amazonaws.com/hireclub-production/sitemaps/sitemap.xml.gz", status: 301)
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  authenticate :user, lambda { |u| u.is_admin } do
    mount Sidekiq::Web => '/sidekiq'
  end


  get 'notifications' => 'notifications#index', as: :notifications
  get 'search' => 'search#index', as: :search
  get 'search/jobs' => 'search#jobs'
  get 'search/projects' => 'search#projects'
  get 'search/members' => 'search#members'
  get 'search/companies' => 'search#companies'

  get 'feed', to: "feed#index", as: :feed


  resources :stories do
    collection do
      get :drafts
    end
    member do
      get :publish
    end
    resources :comments, module: :stories
  end

  resources :jobs do
    resources :comments, module: :jobs
  end

  resources :review_requests do
    resources :comments, module: :review_requests
  end

  resources :messages, only: [:create]

  resources :conversations do
    collection do
      get :between
    end
  end

  resources :resumes, except: [:edit, :update]
  resources :likes, only: [:index, :new, :create, :destroy]

  resources :badges
  resources :company_imports, only: [:new, :create] do
    collection do
      get "search"
    end
  end

  resources :companies, :constraints => { :id => /[\w\.\-]+/ }, :format => false do
    member do
      get :refresh
      get :follow
      get :unfollow
    end
  end

  resources :user_roles
  resources :roles

  resources :comments, only: [:destroy] do
    member do
      get :like
      get :unlike
    end
  end

  resources :milestones do
    resources :comments, module: :milestones
  end

  resources :projects do
    resources :comments, module: :projects
  end

  resources :user_skills
  resources :skills
  resources :onboarding

  get "/locations",   to: "locations#index",   as: :locations
  get "/privacy",   to: "pages#privacy",   as: :privacy
  get "/about",   to: "pages#about",   as: :about
  get "/contact", to: "pages#contact", as: :contact

  get 'users/username' => 'users#username'
  devise_for :users,
    path:        '',
    path_names:  {:sign_in => 'login', :sign_out => 'logout', :edit => 'settings', :sign_up => "signup"},
    controllers: {registrations: 'registrations',
                  omniauth_callbacks: 'users/omniauth_callbacks' }

  get "/members",   to: "users#index",   as: :members

  resources :users, :only => [:show, :update], :path => '/', :constraints => { :id => /[\w\.\-]+/ }, :format => false do
    member do
      get :print
      get :follow
      get :unfollow
      get :followers
      get :following
    end
  end

  authenticated :user do
    root :to => 'feed#index', as: :authenticated_root
  end

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  root to: "pages#index"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    get_results
  end

  def jobs
    get_results("Job")
    render :index
  end

  def projects
    get_results("Project")
    render :index
  end

  def members
    get_results("User")
    render :index
  end

  def companies
    get_results("Company")
    render :index
  end

  def get_results(type = nil)
    @searchable_type = type
    @query = params[:q]
    @page = params[:page]

    if @searchable_type.present?
      @results = PgSearch.multisearch(@query).where(:searchable_type => @searchable_type).page(@page).per(10)
    else
      @results = PgSearch.multisearch(@query).page(@page).per(10)
    end
  end
end

app/views/search/_project.html.haml
= cache [project] do
  - user = project.user
  .media
    = link_to image_tag(model_image(project.image, 800, 600, true), width: 200, class: 'd-flex mr-3 rounded'), project
    .media-body
      %h5.mt-0
        = link_to project.name, project
      %small
        .media
          = link_to image_tag(model_avatar(user.avatar, 200, true), width: 24, class: 'd-flex mr-1 rounded-circle'), user
          .media-body
            = link_to user.display_name, user
            - if project.company
              ·
              = link_to project.company.name, project.company
            - if project.skills_list.present?
              ·
              = project.skills_list
              

  %hr

app/views/search/index.html.haml
- set_meta_tags title: "Search Results"
.sub_nav
  .container
    %ul.nav.nav-pills
      = nav_link_to 'All', search_path(q: params[:q]), {class: 'nav-link'}, { :wrapper => 'li', :wrapper_class => "nav-item", ignore_params: true }
      = nav_link_to 'Jobs', search_jobs_path(q: params[:q]), {class: 'nav-link'}, { :wrapper => 'li', :wrapper_class => "nav-item", ignore_params: true }
      = nav_link_to 'Projects', search_projects_path(q: params[:q]), {class: 'nav-link'}, { :wrapper => 'li', :wrapper_class => "nav-item", ignore_params: true }
      = nav_link_to 'Members', search_members_path(q: params[:q]), {class: 'nav-link'}, { :wrapper => 'li', :wrapper_class => "nav-item", ignore_params: false }
      = nav_link_to 'Companies', search_companies_path(q: params[:q]), {class: 'nav-link'}, { :wrapper => 'li', :wrapper_class => "nav-item", ignore_params: false }

.container.mt-3

  %h5.mb-3
    = "Search Results for \"#{params[:q]}\""
  - @results.each do |result|
    - if result.searchable_type == "Company"
      = render partial: "/companies/company", locals: {company: result.searchable}
    - elsif result.searchable_type == "User"
      = render partial: "/users/user", locals: {user: result.searchable}
    - elsif result.searchable_type == "Job"
      = render partial: "/jobs/job", locals: {job: result.searchable}
    - elsif result.searchable_type == "Project"
      = render partial: "/search/project", locals: {project: result.searchable}      

  = paginate @results

  