config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  get '/sitemap.xml', to: redirect("https://s3-us-west-1.amazonaws.com/hireclub-production/sitemaps/sitemap.xml.gz", status: 301)
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  authenticate :user, lambda { |u| u.is_admin } do
    mount Sidekiq::Web => '/sidekiq'
  end


  get 'notifications' => 'notifications#index', as: :notifications
  get 'search' => 'search#index', as: :search
  get 'search/jobs' => 'search#jobs'
  get 'search/projects' => 'search#projects'
  get 'search/members' => 'search#members'
  get 'search/companies' => 'search#companies'

  get 'feed', to: "feed#index", as: :feed


  resources :stories do
    collection do
      get :drafts
    end
    member do
      get :publish
    end
    resources :comments, module: :stories
  end

  resources :jobs do
    resources :comments, module: :jobs
  end

  resources :review_requests do
    resources :comments, module: :review_requests
  end

  resources :messages, only: [:create]

  resources :conversations do
    collection do
      get :between
    end
  end

  resources :resumes, except: [:edit, :update]
  resources :likes, only: [:index, :new, :create, :destroy]

  resources :badges
  resources :company_imports, only: [:new, :create] do
    collection do
      get "search"
    end
  end

  resources :companies, :constraints => { :id => /[\w\.\-]+/ }, :format => false do
    member do
      get :refresh
      get :follow
      get :unfollow
    end
  end

  resources :user_roles
  resources :roles

  resources :comments, only: [:destroy] do
    member do
      get :like
      get :unlike
    end
  end

  resources :milestones do
    resources :comments, module: :milestones
  end

  resources :projects do
    resources :comments, module: :projects
  end

  resources :user_skills
  resources :skills
  resources :onboarding

  get "/locations",   to: "locations#index",   as: :locations
  get "/privacy",   to: "pages#privacy",   as: :privacy
  get "/about",   to: "pages#about",   as: :about
  get "/contact", to: "pages#contact", as: :contact

  get 'users/username' => 'users#username'
  devise_for :users,
    path:        '',
    path_names:  {:sign_in => 'login', :sign_out => 'logout', :edit => 'settings', :sign_up => "signup"},
    controllers: {registrations: 'registrations',
                  omniauth_callbacks: 'users/omniauth_callbacks' }

  get "/members",   to: "users#index",   as: :members

  resources :users, :only => [:show, :update], :path => '/', :constraints => { :id => /[\w\.\-]+/ }, :format => false do
    member do
      get :print
      get :follow
      get :unfollow
      get :followers
      get :following
    end
  end

  authenticated :user do
    root :to => 'feed#index', as: :authenticated_root
  end

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  root to: "pages#index"
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  # Extensions
  extend FriendlyId
  friendly_id :slug

  # Scopes
  scope :by_recent, -> {order(updated_at: :desc)}

  # Associations
  has_many :messages, dependent: :destroy
  has_many :conversation_users, dependent: :destroy
  has_many :users, through: :conversation_users

  # Validations
  validates :slug, :uniqueness => true, :presence => true
  validates :key, uniqueness: {case_sensitive: false}, :allow_blank => true

  # Callbacks
  before_validation :ensure_slug, on: :create
  before_validation :update_key

  def ensure_slug
    if slug.blank?
      self.slug = loop do
        slug = SecureRandom.hex(8)
        break slug unless Conversation.where(slug: slug).exists?
      end
    end
  end

  def update_key
    self.key = Conversation.key_for_users(self.users)
  end

  def other_users(user)
    self.users - [user]
  end

  def last_message
    messages.by_recent.last
  end

  def unread_messages_count(user)
    conversation_users.where(user: user).first.try(:unread_messages_count)
  end

  def self.key_for_users(users)
    users.sort.map(&:id).join("_")
  end

  def self.between(users)
    key = self.key_for_users(users)

    conversation = Conversation.where(key: key).first_or_create
    conversation.users = users
    conversation.save
    return conversation
  end

  def update_unread_counts
    conversation_users.each do |conversation_user|
      conversation_user.update_unread_messages_count
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_conversations, only: [:index, :show]
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized, except: [:index]

  # GET /conversations
  def index
    redirect_to current_user.conversations.by_recent.first if current_user.conversations.any?
  end

  def between
    users = User.find(params[:user_ids])
    conversation = Conversation.between(users)
    authorize conversation
    redirect_to conversation
  end

  # GET /conversations/1
  def show
    @other_users = @conversation.other_users(current_user)
    @message = Message.new
    @messages = @conversation.messages.by_recent
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
    authorize @conversation
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  def create
    @conversation = Conversation.new(conversation_params)
    authorize @conversation

    if @conversation.save
      redirect_to @conversation, notice: 'Conversation was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /conversations/1
  def update
    if @conversation.update(conversation_params)
      redirect_to @conversation, notice: 'Conversation was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /conversations/1
  def destroy
    @conversation.destroy
    redirect_to conversations_url, notice: 'Conversation was successfully destroyed.'
  end

  private

    def set_conversations
      @conversations = current_user.conversations.by_recent
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.friendly.find(params[:id])
      authorize @conversation
    end

    # Only allow a trusted parameter "white list" through.
    def conversation_params
      params.require(:conversation).permit(:slug)
    end
end

app/views/conversations/_conversation.html.haml
- other_user = conversation.other_users(current_user).first
- classes = "list-group-item list-group-item-action conversation_cell"
- classes += " active" if conversation.id == @conversation.id
= link_to conversation_path(conversation), class: classes, id: "conversation_#{conversation.id}" do
  .media
    .presence_container.mr-3
      = image_tag(model_avatar(other_user.avatar, 200, true), width: 48, class: 'd-flex rounded-circle')
      .presence{data: {behavior: "presence", "user-id": other_user.id}}
        &nbsp;
    .media-body
      = other_user.short_display_name
      %small.conversation_time.text-muted
        = local_time(conversation.updated_at, "%l:%M%P")
        - unread_count = conversation.unread_messages_count(current_user)
        - if unread_count > 0
          %span.badge.badge-primary.text-right{ data: {count: "#{unread_count}"}}
            = unread_count

      %p.mb-0
        %small.conversation_preview
          - last_message = conversation.last_message
          - if last_message
            - if last_message.user == current_user
              You:
            = truncate(conversation.last_message.text, length: 25)

app/views/conversations/_form.html.haml
= form_for @conversation do |f|
  - if @conversation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@conversation.errors.count, "error")} prohibited this conversation from being saved:"
      %ul
        - @conversation.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :slug
    = f.text_field :slug
  .actions
    = f.submit 'Save'

app/views/conversations/edit.html.haml
%h1 Editing conversation

= render 'form'

= link_to 'Show', @conversation
\|
= link_to 'Back', conversations_path

app/views/conversations/index.html.haml
.container-fluid.mt-2.mb-5
  - title "Conversations"

  .row
    = render "conversation_list"
    

app/views/conversations/new.html.haml
%h1 New conversation

= render 'form'

= link_to 'Back', conversations_path

app/views/conversations/show.html.haml
- title @other_users.map(&:display_name).join(", ")

.container-fluid.conversations_container.px-0
  .row.m-0
    .col-sm-4.col-md-3.px-0
      #conversations_container
        #conversations_header
          .text-center
            Messages
        #conversation_list
          .list-group#conversations
            = render @conversations
    .col-sm-8.col-md-9.px-0
      #messages_container
        #messages_header
          - other_user = @other_users.first
          .media
            = link_to image_tag(model_avatar(other_user.avatar, 200, true), width: 48, class: 'd-flex mr-3 rounded-circle'), other_user, target: "_blank"
            .media-body
              %strong
                = link_to other_user.display_name, other_user, target: "_blank"
              %p
                %small
                  = other_user.primary_role_name
                  - if other_user.company
                    ·
                    = other_user.company.name
                  - if other_user.location.present?
                    ·
                    = other_user.location.name

        #messages{ data: {behavior: "messages", "conversation-id": @conversation.id}}
          - if @messages.any?
            - last_message = nil
            - unread = false
            - @messages.each do |message|
              - if last_message.nil?
                .day_cell
                  = local_time_ago(message.created_at)
              - elsif message.created_at.to_date != last_message.created_at.to_date
                .day_cell
                  = local_time_ago(last_message.created_at)
              /condition to check whether message by other users are read by current user
              - if message.user != current_user && !unread && !message.is_read_by?(current_user)
                - unread = true
                .unread_cell
                  Unread
              = render message
              - last_message = message

          #typing_indicator
            .message
              .message_bubble
                •••
        #messages_input
          = form_for @message do |f|
            = f.hidden_field :conversation_id, value: @conversation.id
            = f.text_area :text, class: 'form-control', placeholder: "Type your message", autocomplete: "off", autofocus: true, rows: 1