config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  get '/sitemap.xml', to: redirect("https://s3-us-west-1.amazonaws.com/hireclub-production/sitemaps/sitemap.xml.gz", status: 301)
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  authenticate :user, lambda { |u| u.is_admin } do
    mount Sidekiq::Web => '/sidekiq'
  end


  get 'notifications' => 'notifications#index', as: :notifications
  get 'search' => 'search#index', as: :search
  get 'search/jobs' => 'search#jobs'
  get 'search/projects' => 'search#projects'
  get 'search/members' => 'search#members'
  get 'search/companies' => 'search#companies'

  get 'feed', to: "feed#index", as: :feed


  resources :stories do
    collection do
      get :drafts
    end
    member do
      get :publish
    end
    resources :comments, module: :stories
  end

  resources :jobs do
    resources :comments, module: :jobs
  end

  resources :review_requests do
    resources :comments, module: :review_requests
  end

  resources :messages, only: [:create]

  resources :conversations do
    collection do
      get :between
    end
  end

  resources :resumes, except: [:edit, :update]
  resources :likes, only: [:index, :new, :create, :destroy]

  resources :badges
  resources :company_imports, only: [:new, :create] do
    collection do
      get "search"
    end
  end

  resources :companies, :constraints => { :id => /[\w\.\-]+/ }, :format => false do
    member do
      get :refresh
      get :follow
      get :unfollow
    end
  end

  resources :user_roles
  resources :roles

  resources :comments, only: [:destroy] do
    member do
      get :like
      get :unlike
    end
  end

  resources :milestones do
    resources :comments, module: :milestones
  end

  resources :projects do
    resources :comments, module: :projects
  end

  resources :user_skills
  resources :skills
  resources :onboarding

  get "/locations",   to: "locations#index",   as: :locations
  get "/privacy",   to: "pages#privacy",   as: :privacy
  get "/about",   to: "pages#about",   as: :about
  get "/contact", to: "pages#contact", as: :contact

  get 'users/username' => 'users#username'
  devise_for :users,
    path:        '',
    path_names:  {:sign_in => 'login', :sign_out => 'logout', :edit => 'settings', :sign_up => "signup"},
    controllers: {registrations: 'registrations',
                  omniauth_callbacks: 'users/omniauth_callbacks' }

  get "/members",   to: "users#index",   as: :members

  resources :users, :only => [:show, :update], :path => '/', :constraints => { :id => /[\w\.\-]+/ }, :format => false do
    member do
      get :print
      get :follow
      get :unfollow
      get :followers
      get :following
    end
  end

  authenticated :user do
    root :to => 'feed#index', as: :authenticated_root
  end

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  root to: "pages#index"
end

app/models/badge.rb
class Badge < ApplicationRecord
  include Searchable
  extend FriendlyId
  friendly_id :name, use: :slugged
  dragonfly_accessor :avatar

  # Scopes
  scope :by_name, -> { order('name ASC') }
  scope :by_position, -> { order(position: :asc) }

  # Associations
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  # Validations
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :slug, presence: true, uniqueness: {case_sensitive: false}

  def self.reward_og_badge(user)
    badge = Badge.where(name: "Original Gangsta").first
    Badge.reward(user, badge)
  end

  def self.reward_skill_badge(user)
    badge = Badge.where(name: "Skillz").first
    Badge.reward(user, badge)
  end

  def self.reward_skill10_badge(user)
    badge = Badge.where(name: "Brainz").first
    Badge.reward(user, badge)
  end

  def self.reward_milestone_badge(user)
    badge = Badge.where(name: "Milestoned").first
    Badge.reward(user, badge)
  end

  def self.reward_milehigh_badge(user)
    badge = Badge.where(name: "Mile High Club").first
    Badge.reward(user, badge)
  end

  def self.reward_project_badge(user)
    badge = Badge.where(name: "ProPro").first
    Badge.reward(user, badge)
  end

  def self.reward_moderator_badge(user)
    badge = Badge.where(name: "Mod").first
    Badge.reward(user, badge)
  end

  def self.reward_hired_badge(user)
    badge = Badge.where(name: "HireClubbed!").first
    Badge.reward(user, badge)
  end

  def self.reward(user, badge)
    user_badge = UserBadge.where(user: user, badge: badge).first_or_create
  end

  def self.seed
    badge = Badge.where(name: "Original Gangsta").first_or_create
    badge.update_attributes(
      description: "Original HireClub group member.",
      earned_by: "being part of HireClub group before launch."
    )

    badge = Badge.where(name: "Skillz").first_or_create
    badge.update_attributes(
      description: "Skillz to pay the bills.",
      earned_by: "adding 5 skills."
    )

    badge = Badge.where(name: "Brainz").first_or_create
    badge.update_attributes(
      description: "Smarty Pants",
      earned_by: "adding 10 skills."
    )

    badge = Badge.where(name: "Milestoned").first_or_create
    badge.update_attributes(
      description: "You are going places kid.",
      earned_by: "adding 5 milestones."
    )

    badge = Badge.where(name: "Mile High Club").first_or_create
    badge.update_attributes(
      description: "Nothin gonna stop us now.",
      earned_by: "adding 10 milestones."
    )

    badge = Badge.where(name: "ProPro").first_or_create
    badge.update_attributes(
      description: "Looking fly AF.",
      earned_by: "adding 3 projects."
    )

    badge = Badge.where(name: "Mod").first_or_create
    badge.update_attributes(
      description: "HireClub posse in the house.",
      earned_by: "being a moderator."
    )

    badge = Badge.where(name: "HireClubbed!").first_or_create
    badge.update_attributes(
      description: "YOU GOT THE JOB!",
      earned_by: "getting hired through HireClub."
    )

    badge = Badge.where(name: "Team").first_or_create
    badge.update_attributes(
      description: "Hired by HireClub. Whoa.",
      earned_by: "working for HireClub."
    )

    # badge = Badge.where(name: "Mile High Club").first_or_create
    # badge.update_attributes(
    #   description: "Go on wit yo bad self",
    #   earned_by: "adding 6 projects."
    # )
  end

  def self.check_badges
    User.all.find_each do |user|
      if user.user_skills.count >= 5
        Badge.reward_skill_badge(user)
        if user.user_skills.count >= 10
          Badge.reward_skill10_badge(user)
        end
      end

      if user.milestones.count >= 5
        Badge.reward_milestone_badge(user)
        if user.milestones.count >= 10
          Badge.reward_milehigh_badge(user)
        end
      end

      if user.projects.count >= 3
        Badge.reward_project_badge(user)
      end

    end
  end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  after_action :verify_authorized, except: [:index]
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  def index
    scope = Badge.by_position
    @badges = scope.page(params[:page]).per(10)
  end

  # GET /badges/1
  def show
    @users = @badge.users.page(params[:page])
  end

  # GET /badges/new
  def new
    @badge = Badge.new
    authorize @badge
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  def create
    @badge = Badge.new(badge_params)
    authorize @badge

    if @badge.save
      redirect_to @badge, notice: 'Badge was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /badges/1
  def update
    if @badge.update(badge_params)
      redirect_to @badge, notice: 'Badge was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /badges/1
  def destroy
    @badge.destroy
    redirect_to badges_url, notice: 'Badge was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.friendly.find(params[:id])
      authorize @badge
    end

    # Only allow a trusted parameter "white list" through.
    def badge_params
      params.require(:badge).permit(:name, :slug, :description, :earned_by, :position,
        :avatar, :retained_avatar, :remove_avatar, :avatar_url
      )
    end
end

app/views/badges/_badge.html.haml
= cache [badge] do
  .media
    = link_to image_tag(model_image(badge.avatar, 200, 200, true), width: 52, class: 'd-flex mr-3 rounded'), badge
    .media-body
      %h5.mt-0.mb-0
        = link_to badge.name, badge
      
      = badge.description
      %p.mb-0
        %small
          Earned by
          = badge.earned_by

  %hr

app/views/badges/_form.html.haml
= form_for @badge do |f|
  - if @badge.errors.any?
    #error_explanation
      %h2= "#{pluralize(@badge.errors.count, "error")} prohibited this badge from being saved:"
      %ul
        - @badge.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-6
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control', autocomplete: :off
      .form-group
        = f.label :slug
        = f.text_field :slug, class: 'form-control'
      .form-group
        = f.label :description
        = f.text_field :description, class: 'form-control'
      .form-group
        = f.label :earned_by
        = f.text_field :earned_by, class: 'form-control'
      .form-group
        = f.label :position
        = f.number_field :position, class: 'form-control'

    .col-6
      .form-group
        = f.label 'Avatar'
        %br
        = image_tag(model_image(@badge.avatar, 200, 200, true), width: 100, class: 'm-b-1')
        %br
        = f.file_field :avatar
        = f.hidden_field :retained_avatar
        = f.text_field :avatar_url, class: 'form-control', placeholder: "http://site.com/image.jpg"

  
  %hr
  = f.submit 'Save', class: 'btn btn-primary btn-lg'

app/views/badges/edit.html.haml
.container.content_container
  %h1= "Edit #{@badge.name}"

  = render 'form'

  = link_to 'Show', @badge
  

app/views/badges/index.html.haml
.container.content_container
  %h1 
    = title "Badges"
    %small
      = link_to 'New', new_badge_path, class: "btn btn-primary btn-sm" if policy(Badge).new?
  %p
    %small
      = pluralize(Badge.all.count, "badge")

  .badges.mt-4
    = render @badges

  = paginate @badges

app/views/badges/new.html.haml
.container.content_container
  %h1= title "New Badge"

  = render 'form'

  = link_to 'Back', badges_path

app/views/badges/show.html.haml
.container.content_container
  .row
    .col-sm-8
      .media
        = image_tag(model_image(@badge.avatar, 200, 200, true), width: 100, class: "d-flex mr-3 rounded")
        .media-body
          %h1.black
            = title @badge.name
          = @badge.description
          %p
            %small
              Earned By
              = @badge.earned_by
              %br
              = pluralize(@badge.users.count, "member")
    .col-sm-3
      = link_to 'Edit', edit_badge_path(@badge), class: "btn btn-primary btn-block" if policy(@badge).edit?
  .row
    .col-sm-12
      = render partial: "users/user", collection: @users 

      = paginate @users